version: '3'
services:
    postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: demo
        volumes:
        - "postgres:/var/lib/postgresql/data"
        ports:
        - "5432:5432"
    back:
        image: node:8.16.2-jessie-slim
        working_dir: /var/api/src
        volumes:
        - "./api:/var/api"
        environment:
            DATABASE_URL: ${POSTGRES_URI}
            PORT: ${PORT}
        ports:
        - ${PORT}:${PORT}
        depends_on:
        - postgres
        tty: true

volumes:
    postgres: