version: '3'
services:
    postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: demo
        volumes:
        - "postgres:/var/lib/postgresql/data"
        ports:
        - "5432:5432"
    back:
        image: node:12.13.1-buster-slim
        working_dir: /var/api/src
        volumes:
        - "./api:/var/api"
        environment:
            SUPER_DELL: ${SUPER_DELL}
            END_POINT_URL: ${END_POINT_URL}
            DATABASE_URL: ${POSTGRES_URI}
            PORT: ${PORT}
        ports:
        - ${PORT}:${PORT}
        depends_on:
        - postgres
        tty: true

volumes:
    postgres: